book:
  length_name: 100
  pagi: 6
  name: "name"
  cate: "categories_id"
  author: "author_id"
  publish: "publisher_id"
  pub_day: "publish_day"
  num_page: "num_pag"
categories:
  length_name: 30
users:
  max_name: 50
  max_email: 150
  min_pass: 6
